/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/f1car.glb --transform 
Files: public/models/f1car.glb [6.22MB] > D:\portfolio-v1\my-app\f1car-transformed.glb [603.4KB] (90%)
Author: Dave Love SketchFab (https://sketchfab.com/Tyler_Dave)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2011-redbull-rb7-8fea3279f3134f64904c1187ebb9dcf8
Title: 2011 Redbull RB7
*/

import React from 'react'
import { GroupProps } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function F1car(props: GroupProps) {
  const { nodes, materials } = useGLTF('/models/f1car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.mirrors} scale={0.01} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.rb_rims} scale={0.01} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.BRAKE} scale={0.01} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Tyre_thread} scale={0.01} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.carbon_fiber} scale={0.01} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.CLEARLED} scale={0.01} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.FER_BLGLOWA} scale={0.01} />
      <mesh geometry={nodes.Object_99.geometry} material={materials.generic_lcd} scale={0.01} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.int_digi_inds} scale={0.01} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.int_infopod} scale={0.01} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.digi_speed} scale={0.01} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.Metal} scale={0.01} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.body} scale={0.01} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.body_0} scale={0.01} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.sw_decals} scale={0.01} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.c_redbull_10_steeringwheel} scale={0.01} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.steering_carbon} scale={0.01} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.cockpit} scale={0.01} />
      <mesh geometry={nodes.Object_165.geometry} material={materials.cockpit_cf} scale={0.01} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.glass} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/f1car-transformed.glb')
